name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Debug Token
      run: |
        echo "Token: ${{ secrets.PAT_TOKEN }}"
        curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" https://api.github.com/rate_limit

    - name: Update dependency graph
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # or ${{ secrets.GITHUB_TOKEN }}
      uses: advanced-security/maven-dependency-submission-action@v3
